### PR TITLE
[WIP] fixes for issues w/internal hiscores, content loading, and samples + libretro-common update

### PR DESCRIPTION
**Pull request by markwkidd**
This PR brings over fixes from mame2003-plus for:

* the internal hiscore database - now using a pleasingly straightforward implementation based on the new nvram bootstraps
* content loading - cleanly exits and logs an error when passed content with no extension rather than segfaulting - originally @grant2258 's work
* fixed a regression with regard to options.use_samples probably from the last batch of backports. with this, behavior should correctly be to use samples if they exist and proceed without if they are missing

There would only be a handful of files changed except that mame2003-plus is on a later version of libertro-common, so those the libretro-common source had to be updated too.

### CODE REVIEW

**Comment by grant2258** [comment]
how do i do a localy pull req ?

can i just do a git checkout 62a936e

**Comment by markwkidd** [comment]
PR's always correspond to a branch, in this case it's a branch on my fork of the mame2003 repo

```
git clone http://github.com/markwkidd/mame2003-libretro markmame
cd markmame
git checkout mame2003-plus-backports
```

**Comment by grant2258** [comment]
think i got it added 

fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
to origin


then done 
git fetch origin

git checkout origin/pr/367
Note: checking out 'origin/pr/367'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 62a936e... samples always on if sample files are present

hope this is right compiling now :)

**Comment by grant2258** [comment]
samples not working the other two problems are fixed though

**Comment by grant2258** [comment]
ill do dome more debugging

**Comment by markwkidd** [comment]
Since I don't have a full romset collection here, could you tell me one of
the games whose samples are the same with mame2003 and mame2003-plus so I
can troubleshoot this further?

I got so confused with all the `dkong` sample talk that I don't know what
is a good one to quickly test whether it's functioning or not.

**Comment by grant2258** [comment]
i test with berzerk and dkong

**Comment by grant2258** [comment]
@markwkidd found the problem mate

* user generated content goes in mam2003 save directory subfolders */
         snprintf(currDir, 1024, "%s%s%s%s%s", options.libretro_save_path, path_default_slash(), APPNAME, path_default_slash(), paths[pathtype]);
break;

**Comment by grant2258** [comment]
well we have that problem we had before where the retroarch config inot saving around the time we where fixing robocop

**Comment by markwkidd** [comment]
OK, I will bring osd_get_path over from mame2003-plus

**Comment by grant2258** [comment]
@markwkidd it was arounf 20 days ago 

https://github.com/libretro/mame2003-plus-libretro/pull/94

we had odd results testing with robocop it was something to do with the files

**Comment by markwkidd** [comment]
@grant2258 I just pushed the osd_file functions from -plus into this core. I can now hear Mario jumping in `dkong` which I guess means samples are ok?

**Comment by grant2258** [comment]
should be ill compile and test

**Comment by dankcushions** [comment]
for me this PR is too large. 67 files changes and some diffs are too large to even view

can we have the libretro common updates in a separate PR, please? these monster PRs are impossible to evaluate for me :(

**Comment by grant2258** [comment]
@markwkidd  just do the osd and mame.c fix and leave the segfault the way its always been from day one ill find another way to fix that

**Comment by markwkidd** [comment]
Yeah when I started I didn't realize I'd be updating libretro-common, now I
know that I can split this up better. I was trying to do semantic commits,
I swear!

**Comment by grant2258** [comment]
mark give me a bit I think i can do this

**Comment by markwkidd** [comment]
Thanks, I'm away from keyboard for a while now

**Comment by grant2258** [comment]
right its done mark its basically a carbon copy of your code

**Pull request closed without merging**
