### PR TITLE
fix bally input

### PR DESCRIPTION
**Pull request by grant2258**
just used the mame2000 code for the sample update it works why re invent the wheel we know what the  problem is

### CODE REVIEW

**Comment by dankcushions** [comment]
Please make sure that MK 2 and 3 are retested with this code, as the code that fixed them has been taken out here (maybe it won't be necessary with this new code!)

**Comment by grant2258** [comment]
yep mk2 is running perfect will try 3

**Comment by dankcushions** [comment]
make sure to run both for 20 minutes - the audio distortion doesn't happen until around 10 mins. see https://github.com/libretro/mame2003-libretro/issues/43

**Comment by grant2258** [comment]
just leave them running on demo mode ?

**Comment by dankcushions** [comment]
yeah, demo is fine.

tagging @rtissera (original author of the fix) in case they can spot any potential issues.

**Comment by grant2258** [comment]
running good for ten minutes

**Comment by grant2258** [comment]
I think we need to add the underun and over run code as well to tighten the timing up at a quick look

**Comment by grant2258** [comment]
well the delta does need added heard it rattling a little its not that bad though but does need fixed dont know how bad it was before

**Comment by grant2258** [comment]
ok ive added the mortal combat fix back so it should be fine. ill run it for 20 minutes and let you know. The good news is its not the input system thats a result

**Comment by grant2258** [comment]
mk2 and mk3 are good to go once we get this tightened up a lot will fix itself up. if you comment out the audio cb in you will see robocop runs as it should fos wise . It will get moe into this when i get time. unfortunately I dont think mcr games will not run without the audio the way the inputs are hooked up to the sound

**Comment by twinaphex** [comment]
To all participants involved - let me know if/when this is fit for merging and I will do it.

**Comment by grant2258** [comment]
it sup to you guys it is fit for merging will fix your input issues when running bally games at the wrong framerate (48000)  they will run just not not like should unless you change your sample rate. I will also fix the sound up on bally games when you go back to 22050

**Comment by grant2258** [comment]
actually i figured out what we are doing wrong and why its effecting the frame rate.


osd_start_audio_stream() is called at the start of the emulation to initialize
  the output stream, then osd_update_audio_stream() is called every frame to
  feed new data. osd_stop_audio_stream() is called when the emulation is stopped.

  The sample rate is fixed at Machine->sample_rate. Samples are 16-bit, signed.
  When the stream is stereo, left and right samples are alternated in the
  stream.

  osd_start_audio_stream() and osd_update_audio_stream() must return the number
  of samples (or couples of samples, when using stereo) required for next frame.
  This will be around Machine->sample_rate / Machine->drv->frames_per_second,
  the code may adjust it by SMALL AMOUNTS to keep timing accurate and to
  maintain audio and video in sync when using vsync. Note that sound emulation,
  especially when DACs are involved, greatly depends on the number of samples
  per frame to be roughly constant, so the returned value must always stay close
  to the reference value of Machine->sample_rate / Machine->drv->frames_per_second.
  Of course that value is not necessarily an integer so at least a +/- 1
  adjustment is necessary to avoid drifting over time. 


osd_update_audio_stream() should be running the audio cb ill fix it up on my next days off work  

from os depend.h  we simply need to update the  audio in

**Comment by Wilstorm** [comment]
@grant2258 - Wow, right, ok...I was thinking that was the issue but you beat me to the explanation! ;)

So to clarify on Bally games. We just need to set sample rate to 22050 and they should play proper?

Can that value be set globally from the core options or will it cause other issues and should only be done on a per ROM basis for Bally games? Midway/Bally games??

**Comment by grant2258** [comment]
ive done the fix you wont have to change anything. it changes the sample rate and core timing when it needs too. Your good to push the @twinaphex 

https://github.com/libretro/mame2003-libretro/pull/359/commits/c9865f3075be5dc3bc4a0063a2e7894c26bc6d4e

The only way to avoid this is to stream the sample buffer like mame does

**Comment by grant2258** [comment]
@wilson any below 48fps will be effected like the atari games that dont work it is fixed now the only alternantive is to just stream the audio like mame does and dont use the audio cb

**Comment by twinaphex** [comment]
@dankcushions You mind if I merge this?

**Comment by grant2258** [comment]
yes its all tested if your running 48k samples a frame you cant do on the video at 30. I tested the mk as well the delta code is there. as mentioned above in the text

**Comment by twinaphex** [comment]
OK, merging this then. One final request though - if @dankcushions finds out issues with it later and he raises an issue over it, would you be willing to help then fix some of the issues?

**Comment by grant2258** [comment]
you can revert anything you like I just want to improve the cores. I am willing to try help fix anything we can. I would only request that dankcushions  gives me more information on his info as he seed it on the retrorach timing

**Comment by grant2258** [comment]
https://docs.libretro.com/specs/api/#audio-callback-considerations

**Comment by dankcushions** [comment]
This one seems good, thanks @grant2258! My concern before was with the fps timing stuff as that seems to stop the api being aware of the true frame rate. the current fix approaches this issue from another angle and although it would be cool to get the api to play nice with how mame works this is definitely fine for now!

**Comment by twinaphex** [comment]
Merged, and thanks for your efforts @grant2258 !

**Comment by grant2258** [comment]
@dankcushions @twinaphex  thanks glad we got there the fps thing to me runs right either way. The core changes fps or the video changes fps. Thats another issue all together though

**Pull request merged**
