### PR TITLE
New Working Game : Vasara 2

### PR DESCRIPTION
**Pull request by gamez-fan**

### CODE REVIEW

**Comment by dankcushions** [comment]
this is cool! but i'm not sure how i feel about adding new games outside of mame 0.78 (as I assume this/they are?). they won't be in the romset or currently distributed mame 0.78 romsets. vasara 2 is in https://github.com/libretro/fbalpha, so i'm not sure what the benefit is in adding it to other repos.

what do others thing? @markwkidd

**Comment by markwkidd** [comment]
I think it is a good thing to bring new functionality into mame2003 as long as it seamlessly integrates.

If I understand correctly, this PR backports part of the driver from a future version and adds machine information for vasara 2 and a clone. I have been thinking about scenario this, myself. In particular there are some games with bad/missing ROM dumps but there are drivers that play other games well. There could be a number of these opportunities.

Anyway, in terms of this case, what about taking inspiration from libretro-database? My understanding is that they maintain secondary DATs for hacks and other non-official releases. My proposal is to accept the PR and then maintain a RetroArch DAT and a ClrMamePro DAT for "hacks" in the metadata folder. That way if people want to hunt down the ROMs for this new experience, they will have the tools at hand to do so.

Does that make any sense?

**Comment by gamez-fan** [comment]
The benefit of adding these games is that they might well perform better in this older MAME core over 
FBA on certain platforms..??, also some users might like to have them supported..?? i understand
what your saying with regards to the Romsets though.

**Comment by retro-wertz** [comment]
so whats this going to be now? mame2003 - 2017?

**Comment by dankcushions** [comment]
@markwkidd that sounds good to me! if we can get an extra .dat file then I think this can be accepted, assuming everything works.

**Comment by markwkidd** [comment]
When someone releases a new homebrew SNES ROM, it's likely to 'just work' in SNES emulators. This is running on existing code, it's pretty much the same metadata about loading the ROM not that different from a console emulator heading.

**Comment by markwkidd** [comment]
@gamez-fan what version vasara2.zip and vasara2a.zip romset are you using?

**Comment by gamez-fan** [comment]
Both versions of Vasara 2 are from MAME85

**Comment by gamez-fan** [comment]
I have the Roms for both commits if required

**Comment by markwkidd** [comment]
> `I have the Roms for both commits if required

Are you familiar with the ClrMamePro software? If so, could you please verify your ROMs against this new DAT I have created? Or I guess I should say in this case: could you verify this DAT against your ROMs?

[MAME 2003 Hacks XML.zip](https://github.com/libretro/mame2003-libretro/files/1385590/MAME.2003.Hacks.XML.zip)

**Comment by Darknior** [comment]
Thanks a lot for this back port Gamez-fan it is so excellent :)
New games on MAME are always a good thing. I prefer MAME than FBA and in MAME we have cheat for children :)

**Comment by gamez-fan** [comment]
@markwkidd  i tend to use Romcentre and have it setup and ready to go if you could provide
me with a dat for that software then sure i can check my Roms against it.

**Comment by markwkidd** [comment]
@gamez-fan OK I found a converter utility called DatUtil

Here is it's output if you could please try. Note that it also includes your other addition: https://pastebin.com/5THcqivQ

**Comment by gamez-fan** [comment]
@markwkidd this should be of some help
[url]http://www79.zippyshare.com/v/rzPah1vt/file.html[/url]

**Comment by twinaphex** [comment]
I like the idea of backporting new games to older MAME versions, especially given how much faster these versions are compared to mainline MAME.

**Comment by markwkidd** [comment]
@gamez-fan do you mind sending me an email at mark@stardart.net?

I want to make sure I generate the correct DATs for your backports.

**Comment by gamez-fan** [comment]
@markwkidd drop me a PM over at the retropie site and i'll get back to shortly

**Comment by markwkidd** [comment]
@gamez-fan the retropie forums don't have private messages either, for some reason.

I use the libretro forums as well, which do offer PMs, but I can't find your username registered there . 8-)

**Comment by gamez-fan** [comment]
Here's the Rom for the working version of Counter Run, you have em all now to check against
your dat file......

[url]http://www61.zippyshare.com/v/dUEs3IGq/file.html[/url]

**Pull request merged**
