### PR TITLE
Changed paths to traditional MAME paths

### PR DESCRIPTION
**Pull request by dankcushions**
Avoids confusing users familiar with the old standards (the sample/samples has caught a few out). Not backwards compatible with old version - directories will need to be moved/renamed for it to retrieve them. I thought about making the code check the old locations first, but i think it would be cleaner to move them to the new places via the bash scripts being used to build/install this in the Retropie project. I'm not sure who else is using mame2003, but maybe PR should be kept open for comment (including @joolswills).

**Changed paths**
Old paths:
`/libretro savefile dir/mame2003/config`
`/libretro savefile dir/mame2003/hsdb/hiscore.dat`
`/libretro savefile dir/mame2003/hs`
`/libretro system dir/mame2003/sample`

New paths:
`/libretro savefile dir/mame2003/cfg/` (renamed)
`/libretro system dir/mame2003/hiscore.dat` (now root of system dir)
`/libretro savefile dir/mame2003/hi/` (renamed)
`/libretro system dir/mame2003/samples/` (renamed)

ALSO:
- Updated and prettified README  …
- Exposed cheats (default: disabled) and samples (default:enabled) to core options. when enabled, and with a valid cheat.dat in `/libretro system dir/mame2003/cheat.dat`, cheats now work via the TAB menu.

### CODE REVIEW

**Comment by joolswills** [comment]
I'm happy with the path changes and I think it simplifies it, although the commit contains whitespace changes that would imho be best done as a separate commit (if they are needed to clean up indentation). If not they should be left out.

**Comment by joolswills** [comment]
It is the RetroArch devs opinions that matter though not mine ;-)

**Comment by twinaphex** [comment]
Alright, seems we're good to go then.

**Comment by dankcushions** [comment]
@joolswills agreed - the style nits were especially pointless as the whole thing is inconsistent anyway! i will try and stick to my goal next time :)

**Comment by twinaphex** [comment]
@dankcushions - can you look at the pcsx rearmed repo for Android? I think the JNI Makefile no longer compiles after the last few merges (I think you sent me some from notaz).

http://hastebin.com/xumivitajo

http://hastebin.com/tufesumime
http://hastebin.com/usolijamat

**Comment by dankcushions** [comment]
@twinaphex oh no :( some (all?) of those vars are defined here: https://github.com/notaz/pcsx_rearmed/blob/cc3768145667aef20eab35da0908755d5bd395ab/libpcsxcore/new_dynarec/emu_if.c#L433

but not sure what commit would have caused it. don't have an android device to check :(

**Comment by windale** [comment]
It would be better if you set the cheats option to ON as default because you have to manually turn on the selected cheats for each game anyway.

**Comment by dankcushions** [comment]
@windale it's off by default in the original code, so I just followed that style. it takes two seconds to turn it on forever anyway!

raise an issue for cheats in mame2000 and maybe someone will get to it: https://github.com/libretro/mame2000-libretro/issues

**Comment by windale** [comment]
I was only thinking of new users (retropie is supposed to be user friendly after all). Much like when you added the samples folder as 'sample' and lots of people got confused, so they changed if to the same format that's used on all platforms as standard. I just thought it would make sense to leave the cheats on by default on all mame versions because technically they are still off until you choose an appropriate cheat. Nether mind.

**Comment by dankcushions** [comment]
This isn't retropie. Retropie could easily have these options turned on by default as it supports setting core options on/off within it's configuration.

**Pull request merged**
