### PR TITLE
Revert NBA Jam sound fix

### PR DESCRIPTION
**Pull request by gamez-fan**
People can now choose via the Williams speedhacks options in the GUI to turn em off or on if they want to 
favor a performance boost with the downside that the sound will be worse in a few games

### CODE REVIEW

**Comment by gamez-fan** [comment]
Rob Peter to pay Paul as we might say, this will fix all the games soundwise with the Williams speedhacks disabled but will break NBA Jam voices once again with them actived at least via the recent code
additions people can now choose to activate them or not in the GUI options.

**Comment by msheehan79** [comment]
@gamez-fan As an alternative to completely reverting this change, would it be worth considering adding this to the Williams speedhack core option? If you think this would be a solution I could look at expanding the core option to flip this block of code depending on if the speedhacks are enabled or not?

**Comment by gamez-fan** [comment]
Sure that would always be an option worth considering.

**Comment by gamez-fan** [comment]
Ya know just for the record this isn't a problem with the Williams sound core i ported it was a 
known problem with NBA Jam having missing voices and NBA Jam TE seems to trigger the 
wrong voices over and over with the hacks active hence why the speedups were removed come 
MAME62 i always took the view that games having a few sound niggles was better than them
not being playable on the Xbox minus the hacks.

10th October 2002: Aaron Giles fixed the NBA Jam sounds by removing some speedup hacks, 
as a result the driver will be much slower.

Here lies the problem i've never played the T-Unit version of Mortal Kombat in MAME61 only with
some hacked shortcuty core BritneysPAIRS added to his frontend launcher i mean for all i know he 
hooked up the Y-Unit version of Mortal Kombat to work with that hence why i have it in my head
that the T-Unit Mortal Kombat should work fine soundwise with the speedups active. maybe thats
not the case..?? i'd ask him about this but we're not on talking terms due to him stabbing me in the
back codewise once to often :) 

Anyway if we cant get the games to play with correct sound using this sound core with a speedup on
or off option then we can always just revert back to using the Williams core you had previously and 
make the speedups a feature of the Midway Libretro MAME core and folks on lesser hardware that
have problems performance wise with these games can always just use that core to play em.

food for thought at any rate.

**Comment by msheehan79** [comment]
hmm just thinking out loud a bit here, and this is more of a "is this even possible" question as I'm far from an expert on the inner workings of MAME itself so this idea may not even be an option. 

Right now the core option I added is just toggling those 2 variables you highlighted in the williams_sndhrdw.c file (DISABLE_FIRQ_SPEEDUP / DISABLE_LOOP_CATCHERS), which helps with the sound issue but apparently does not 100% resolve some issues. 

What if instead of toggling values within the williams_sndhrdw.c file, I look at creating a second file, so one would be the original MAME78 version of the williams sound, and a second version containing these speedhacks. I could then see if we could conditionally include either the original version or the speedhack version depending on the core option. I'm thinking if we can do this it would be a cleaner solution as there is a lot of code changes in the file to sift through and conditionally enable/disable otherwise. 

Is that even possible within MAME or are these files hardcoded somewhere?

**Comment by gamez-fan** [comment]
Im gonna test this later with the Williams sound core before your commit and flip off both the
speedhacks as im sure that should fix the sound, like yourself im no expert on MAME code but
i wonder if combining the two speedhacks into one has worked as maybe only one of them
is flipping off leaving the other active hence that might cause there to be some sound issues
still.

With regards to a second Williams sound core i have one i created for my own core but it
has to be different as the build will complain about dublicated code if you try to compile
two files that have the same code handling i had to make mine williams_alt and create
some new sound hooks in the drivers and machine files so the all code ties together
it's a bit of graft to do this and kinda untidy so im not sure of this is a direction the
custodians of this git might wanna travel down.

Im compairing the williams sound core with the hacks and without i've noticed something 
that might or might not be a problem i'll explain it in another post later on and see what ya's
think as it's dinner time now :)

**Comment by gamez-fan** [comment]
Ok as per me testing the games over the last few hours with the speedhacks active we get
the sound problems as reported previously, if however we turn em off then the sound is
WORSE in the games i've tested that use this core certainly Midway T-Unit and Y-Unit
i've not tested Williams games or MCR68 games but going by the above they might well
have worse sound also dunno for sure.

I think as the Williams sound core from MAME61 is built around the speedhacks the code isn't
really setup in such a way as to not use em, i wonder how the sound is for the DCS games should
users turn off the speedhacks in that core also..??

It's an all or nothing deal really either keep em active to get the performance boost and a few games
as reported above will have some sound issues or totally revert the soundcore back to the version you
had previously to be sure the sound will be good in all games using the Williams core

Thats the only advice i can give really.

**Comment by dankcushions** [comment]
I think it should be reverted. we're having users report issues: https://retropie.org.uk/forum/topic/14872/mortal-kombat-new-sound-issues-mame2003

at least with the raspberry pi 3 (not sure about 2), these games were full speed anyway, no? i don't see the benefit in the speedhacks for us, at least beyond the old DCS one.

**Comment by gamez-fan** [comment]
I agree with @dankcushions lets revert the Williams sound core i'll send the push shortly which
along with this one will fix all the sound issues that have been reported.

But for talking sake should we leave them active in the mame-2003_midway build..?? than people
that do have performance issues with these games can just be directed to use that core

**Comment by msheehan79** [comment]
Also agree - I took a look at the Williams sound hardware code last night to see how difficult it would be to make the Core option more comprehensive than just flipping the 2 compiler switches, and it would be quite involved as the audio code changes were pretty significant between these versions. 

If these games run full speed on an RPI3 without the changes I agree the work involved vs. benefit is probably not worth it, especially in light of breaking games that worked fine previously.

@gamez-fan feel free to revert my code changes for the core option as well since it was directly tied to this.

**Pull request merged**
