### PR TITLE
Sound improvements

### PR DESCRIPTION
**Pull request by gamez-fan**
0.88u7: BUT added sample support to Sasuke' (hit.wav, boss_start.wav, shot.wav, boss_attack.wav).
0.88u7: BUT added speech sample support to Fantasy' (ft_voi-0 - ft_voi-b.wav).
0.88u7: BUT added speech sample support to Vanguard' (vg_voi-0 to vg_voi-f.wav).
0.88u7: MAME32 Improved sample support for Rockola driver HD38880 speech by samples. 
0.81u5: Curt Coder added Vanguard SHOTB sound effect.
0.81u4: Curt Coder hooked up SN76477 sound in Fantasy, Nibbler, Pioneer Balloon, Sasuke and Vanguard

### CODE REVIEW

**Comment by gamez-fan** [comment]
Fully tested no Roms have changed but to take advantage of the full range of
sound improvements new samples are needed for Fantasy, Sasuke and Vanguard
these are easily obtained from the old samples folder on Twistys site.

**Comment by Wilstorm** [comment]
Hey @gamez-fan I am trying to build a DAT for these new sound samples but need a little information if possible.

Here's the ROMs in mame2003 that all use vanguard sound samples currently. Each game currently has only 2 sounds. explosion.wav and fire.wav.
fantasy
fantasyj
nibbler
nibblera
pballoon
satansat
vangrdce
zarzon

Which games use fantasy.zip samples and which use vanguard.zip? Do any stay the same?

**Comment by gamez-fan** [comment]
Hi there

You'll need new samples grab em from twistys site, to answer your question..........

Sasuke = Sasuke samples
Fantasy & Pioneer Balloon = Fantasy samples
Satan of Saturn & Vanguard & Zarzon = Vanguard samples
Nibbler doesn't use samples.

**Comment by Wilstorm** [comment]
Thank you! If you look at the "official" DAT it shows them like listed below. All the samples mentioned above have the vanguard samples attached to the ROMs. sample name="explsion.wav" and sample name="fire.wav". 

"nibbler" sampleof="vanguard
"nibblera" cloneof="nibbler" romof="nibbler" sampleof="vanguard

"satansat" sampleof="vanguard"
"zarzon" cloneof="satansat" romof="satansat" sampleof="vanguard"

**Comment by gamez-fan** [comment]
BTW Nibbler doesn't use any samples, here's a breakdown of the samples now required as per
the code changes...........

const char *sasuke_sample_names[] =
{
	"*sasuke",

	// SN76477 and discrete
	"hit.wav",
	"boss_start.wav",
	"shot.wav",
	"boss_attack.wav",

	0
};

const char *vanguard_sample_names[] =
{
	"*vanguard",

	// SN76477 and discrete
	"fire.wav",
	"explsion.wav",

	// HD38880 speech
	"vg_voi-0.wav",
	"vg_voi-1.wav",
	"vg_voi-2.wav",
	"vg_voi-3.wav",
	"vg_voi-4.wav",
	"vg_voi-5.wav",
	"vg_voi-6.wav",
	"vg_voi-7.wav",
	"vg_voi-8.wav",
	"vg_voi-9.wav",
	"vg_voi-a.wav",
	"vg_voi-b.wav",
	"vg_voi-c.wav",
	"vg_voi-d.wav",
	"vg_voi-e.wav",
	"vg_voi-f.wav",

	0
};

const char *fantasy_sample_names[] =
{
	"*fantasy",

	// HD38880 speech
	"ft_voi-0.wav",
	"ft_voi-1.wav",
	"ft_voi-2.wav",
	"ft_voi-3.wav",
	"ft_voi-4.wav",
	"ft_voi-5.wav",
	"ft_voi-6.wav",
	"ft_voi-7.wav",
	"ft_voi-8.wav",
	"ft_voi-9.wav",
	"ft_voi-a.wav",
	"ft_voi-b.wav",

	0
};

**Comment by Wilstorm** [comment]
Ok thanks @gamez-fan so just to verify if you will. Do the the clones use them? List and sample set below. Including satansat and zarzon.

fantasy = fantasy
fantasyj = fantasy
nibbler = NONE
nibblera = NONE
pballoon = fantasy
sasuke = sasuke
satansat = NONE
vanguard = vanguard
vangrdce = vanguard
zarzon = NONE

**Comment by gamez-fan** [comment]
satansat and it's clone zarzon use vanguard samples.

**Pull request merged**
