### PR TITLE
fix bug in c-based MIPS3 emulator

### PR DESCRIPTION
**Pull request by markwkidd**
This is meant to address https://github.com/libretro/mame2003-libretro/issues/38

This patch enables Killer Instinct to run with the Windows x86_64 MAME 2003 core. @dankcushions might you be willing to test this on ARM?

At first I tried your approach, backporting a future working version of mips3.c to work with MAME 0.78. Because of all of the memory functions that changed between MAME 0.78 -> MAME 0.79 I ultimately decided this was beyond my skill.

Then as I continued my research, I found old forum reports that the powerpc ports of MAME stopped working with Killer Instinct between MAME .76 and approximately MAME 0.85 although there was never a specific bug report in the MAME release notes.

Sure enough, the MAME 0.75 MIPS3 code works here in x86_64 land! Having enjoyed more than a few hours on this already, I did not take the bisect down to the level of individual changes but perhaps in the future someone can see exactly which of the differences is responsible for the crash.

### CODE REVIEW

**Comment by twinaphex** [comment]
Should I let @dankcushions test this first before we merge this?

**Comment by markwkidd** [comment]
I don't see how this could hurt anything. But because it's the most code I've committed,  and it comes after a long night of work on the issue, it would feel good to have someone sanity check this PR.

@aphextwin do you mind waiting till Sunday to see if dankcushions or anyone else is available to check my work?

**Comment by dankcushions** [comment]
I'm out of town at the moment but will be able to test this monday/tuesday :)

**Comment by twinaphex** [comment]
OK, I'll merge it already then.

**Comment by markwkidd** [comment]
Thanks! I have just tried out the new buildbot mame2003 core for x86_64 with this patch. Killer Instinct is running in 32-bit and 64-bit Windows now. Woohoo! How well does it run, and does it run on any other platforms? Time will tell.

**Comment by hizzlekizzle** [comment]
Just tested it on my Shield ATV and KI 1 and 2 both fire up and run (with some minor bugs). KI 1 is not quite full speed while KI 2 is pretty far from it. Still, pretty awesome :D

**Comment by twinaphex** [comment]
On ARM it would fall back on the CPU interpreter. So that is actually not quite bad results considering that. With an ARM dynarec for this MIPS CPU, you would probably get fullspeed.

**Comment by dankcushions** [comment]
it works on RPI3! about 2FPS, but it loads ;)

**Comment by Ploggy** [comment]
Works on WiiU too. But as you'd expect its far from playable ;)
But its there :)

**Pull request merged**
