### PR TITLE
m68kcore update

### PR DESCRIPTION
**Pull request by grant2258**
please read the altered beast sprites issue

### CODE REVIEW

**Comment by grant2258** [comment]
If you just want that bug patched and not do a full core  update and keep the old bugs that mame078   came with in the core let me know .its easy enough to fix the one thing because i know whats doing it. it just seems more sensible to update the core and get all the fixes

**Comment by twinaphex** [comment]
Seems like a good idea to just update Mushashi 68K and other existing components like that. I doubt any real regressions would occur, it can only make games work better.

**Comment by grant2258** [comment]
Sounds like  plan.  im just glad the merge worked im not the best with github

**Comment by Darknior** [comment]
I've compiled and try the game now.
All is perfect and working fine. Thanks a lot.

**Comment by grant2258** [comment]
no problem i just came across the issue of the game not working by accident.

**Comment by markwkidd** [comment]
Thanks for taking this project to completion @grant2258 ! I've not been home this week due to work and it was a nice surprise to see this already merged into the codebase now that I'm back

**Comment by grant2258** [comment]
no problems at all mate appreciate all the help you gave me with this as well.

**Pull request merged**
