### PR TITLE
Add some more missing games

### PR DESCRIPTION
**Pull request by gamez-fan**

### CODE REVIEW

**Comment by gamez-fan** [comment]
All the games i've added to the libretro-2003 neogeo driver should work i've not been able 
to test em it would be nice if someone would give em a whirl and let me know either way
i can provide all the Roms for this purpose.

**Comment by gamez-fan** [comment]
One thing to mention is in MAME79 and again for MAME85 the neogeo graphical code was slightly changed in vidhrdw/neogeo this hooks to new rom load tables in the driver which fixes alotta gfx
niggles in a fair few games, also in MAME79 some changes for the sound rom loading improves
the music and sfx in alotta games as well.

Reason i mention this is im adding the new games on spec in the hope they dont need the gfx
or sound improvements i guess we wont know until someone hopefully tests em, now i have
a checkpoint build of libretro2003 on my PC just now where i've updated the neogeo core
to MAME85 to take advantage of the above improvements this also makes sure any of the
games i have added will play perfectly i guess if this sound good to you or not will depend
on if your adverse to rom changes as to use this updated neogeo core will mean having to
source new Roms which can be difficult for older versions

**Comment by Darknior** [comment]
I'm ok to try for you your improvements Gamez-fan :)
I only must be sure to take the good roms to do it ...
Are you ok ? Normally you know where to write me.

**Comment by gamez-fan** [comment]
If you still have the MAMEoXtras Romset kicking around somewhere on your FTP then those ones
will be correct i take it you can compile this Src and create a build for yourself..?? i just want 
someone to try these ones ive added to see if they work correctly or not.........

bbbuster
ghostlop
ironclad
sengoku3
zupapa
kof2001
kof2002
mslug4
rotd
matrim

And yeah im doin fine thanks not had time to read your PM as yet, how about you how ya doin..??

**Comment by Darknior** [comment]
I'm fine thanks :)
Yes i have all your MAMEoXtra set ;)
I stand they accept your commit, i compile and test your games and made my feedback.

**Comment by gamez-fan** [comment]
Thanks it would be nice to know that they actually work, then i can finish off by adding in
the last non supported games like Samurai Showdown 5 Metal Slug 5 SNK Vs Capcom Chaos
and The king Of Fighters 2003

**Comment by Darknior** [comment]
I have made the test 👍 

I'm not sure of the bios to use, i take the one of xbox.
On NEOGEO only two games are working.
- metalsug
- rage of the dragon
The others come bakc to ES menu.

The 4 arcade games works fine.
- countrnb
- hsf2a
- vasara2
- snowboar

**Comment by gamez-fan** [comment]
Ok thanks for testing i'll review the code and add my final patch later.

**Pull request merged**
