### PR TITLE
mame2003-plus backports: flatten options & osd_file + Makefile update

### PR DESCRIPTION
**Pull request by markwkidd**
Here's my crack at porting over all of the updates to mame2003-plus from @twinaphex , @bparker06 , and myself over the weekend.

I have done what I can to avoid sucking up any of the new driver code from mame2003-plus into this PR. A couple of new drivers did move over, which I think I've found and removed. 

This branch is compiling and running `tempest` the way it should in Windows 7 x64/msys2.

### CODE REVIEW

**Comment by grant2258** [comment]
tempest runs fine for me if i delete core and games overrides

**Comment by markwkidd** [comment]
Excellent!

**Comment by markwkidd** [comment]
Yep @dankcushions I wish I had seen `ctrlr.txt` earlier in my mame2003 career -- it might have helped me! I tried to think: "where should this info be located so that the next person working on input code will see it?" `inputprt.c` seems to fit the bill.

**Comment by grant2258** [comment]
sorry i dint clarify my last statement tempest runs fine for me without this pull req if a delete any over_rides before the this pr

**Comment by markwkidd** [comment]
I didn't state things very well -- I am using `tempest` to make sure that this PR doesn't break anything.

If `tempest` works before and after the PR I feel pretty good -- starting that game uses a pretty good cross-section of the file functions. Directories are created if need, NVRAM is created/loaded, etc. :)

**Comment by grant2258** [comment]
i havent tried this pr yet. Im really bad with github dont  even know how to grab pr. That why i work on my own github page. Until i get more time to get into git hub ill do it this way. Ill just clone it to my github and pull there

**Comment by markwkidd** [comment]
I'm going to reveal that I'm a github newbie with my next statement, but I currently keeping separate `git clone` copies of these repositories on my local machine so I can grab whatever someone is working on:

* libretro/mame2003-plus-libretro
* libretro/mame2003-libretro
* markwkidd/mame2003-libretro
* grant2258/mame2003-libretro

When I want to look at something I do a `git pull` and a `git checkout` (if necessary) in the local folder. If you have a clone of my `mame2003-libretro` repository you could do `git checkout mame2003-plus-backports` and then you would have the code from this PR in your local repository.

I assume there are git workflows that would require fewer local cloned repositories, but this approach is working ok for me. :man_shrugging:

**Comment by grant2258** [comment]
im glad it not just me you way sounds a lot better to me.

i just do a 

git clone https://github.com/libretro/mame2003-libretro.git

cd into direcory


git remote add original https://github.com/libretro/mame2003-libretro.git



before i start any work i make sure im in sync with the original repo


git fetch original
git checkout master
git reset --hard original/master
git push origin master --force

that makes my repo up to date with whats on the original master

git branch fix
git checkout fix 

do the fixes

test

git add -u
git commit

git checkout master
git merge fix
git push

do a pull req

**Comment by markwkidd** [comment]
The only thing I would say about your workflow @grant2258 is that you might want to use git "branches". `git checkout -b new-branch-name` starts a new branch with whatever changes you are making to your code.

Then when you `git push` after you are done working on your code locally, git will prompt you with the command necessary to add that branch to the remote copy of the repository. Branches let you more easily share a work in progress (or create a PR) than working in your `master` branch by default.

Honestly though if your workflow is working there is no need to change it!

**Comment by grant2258** [comment]
ill try add the -b i was just using information from here https://retropie.org.uk/forum/topic/10683/getting-started-with-es-development

**Pull request merged**
