### PR TITLE
adjust dkong palette to match observed rgb values from fbneo

### PR DESCRIPTION
**Pull request by timcannell**
This modification brings the palette used in dkong exactly in line with that of FBNeo which is considered to be correct. The main change in appearance is that the  platforms along which the barrels roll and Mario climbs now have a deep pink colour as oppose to red.
dkong

### CODE REVIEW

**Comment by barbudreadmon** [comment]
As already mentioned in your topic on retropie's forum, this is not a good idea, some users are using this core because they have a preference for the bad reddish colors.

You should implement it as something that can be toggled.

**Comment by timcannell** [comment]
Really ?!

**Comment by Wilstorm** [comment]
@barbudreadmon - I hear what you’re saying and respect your opinion but this seems really out of character for you. It’s a color change, for the better. He’s making the core more accurate on his own time and none of the core guys have an issue. It seem like a win-win for m3plus. You’re the only pushing folks over to FBNeo or other cores. I just don’t know what to add to that, it’s a patch for the better and I guess if people start raining down complaints in mass then it could be rolled back easy enough. I have to say I like it!! :)

**Comment by timcannell** [comment]
I disagree and dont think I'm mistaken at all.

Let's be clear, we are not talking about accommodating a new controller, a
discrete hardware sound which cannot easily be emulated, or something which
facilitates access to the game on a different platform.

We are talking about a fundamental misrepresentation on screen - the screen
is perfectly capable of displaying an accurate colour.

So no, I'm not totally mistaken. But yes mame2003-plus is also a good
candidate for a fix.

**Comment by barbudreadmon** [comment]
>It seem like a win-win for m3plus.

Indeed, as i said, but here is not the m3plus repo.

>So no, I'm not totally mistaken.

You are totally mistaken about emulation not having to accommodate unusual preferences, most emulators have settings causing games to have a different behavior from real hardware. I myself was requested to unfix things in FBNeo for one reason or another, and ended up turning them into togglable settings.

**Comment by timcannell** [comment]
But I'm not 'totally mistaken' about the bad colors issue here... your argument is hard take seriously.

**Comment by Wilstorm** [comment]
> Indeed, as i said, but here is not the m3plus repo

Ooops...my bad, thanks, I follow both cores and missed that! ;-) @timcannell - This is a sister core. A really short history is this core is mostly static. Some of the RetroPie devs complained about changes to this core so it was decided to leave it static and mame2003-plus was born. 

Mame2003-plus has many changes, modern additions and some partial "rewrites" or code changes like Midway games, etc. etc. I would add it to that core. It's basically everything mame2003 is PLUS more. :) If folks want the original colors than mame2003 is a perfect snapshot for that.

Here's the mame2003-plus repo if you want to add it there. I think it's a great addition and thanks for sharing and offering it for others to use!

https://github.com/libretro/mame2003-plus-libretro

**Comment by Wilstorm** [comment]
That being said I still think it doesn't change the ROM set and doesn't break anything so it could be added here too if the core devs wanted it.

**Comment by timcannell** [comment]
Thanks will do 👍

**Comment by timcannell** [comment]
I'll leave it with you guys😉

**Comment by timcannell** [comment]
Just to give some context as to my motivation, my Retropie system only needs to emulate a few dozen or so games nearly all pre ~1985. Mame 2003 was and is fine for my needs with the exception of this colour issue ;-).

**Comment by timcannell** [comment]
> 

Missing semi-colon committed

**Comment by barbudreadmon** [comment]
>fbneo doesnt even have a toggle

FBNeo is not meant to be a 20 years old frozen-in-time snapshot of an emulator, and we only implement those "revert toggle" by request.

>yourself been treated so poorly

No one was treated poorly, except maybe the users with unusual preferences. I explained why this is a bad idea with sound arguments.

**Comment by timcannell** [comment]
> >fbneo doesnt even have a toggle
> 
> FBNeo is not meant to be a 20 years old frozen-in-time snapshot of an emulator, and we only implement those "revert toggle" by request.
> 
> >yourself been treated so poorly
> 
> No one was treated poorly, except maybe the users with unusual preferences. I explained why this is a bad idea with sound arguments.

I don't think they are *sound* at all !!

**Comment by barbudreadmon** [comment]
@timcannell Well, i don't understand your reluctance about adding this as a togglable setting, but ok, disregard the first sentence of this repo's readme, and disregard the users with unusual preferences. It's not really my problem, and i trust @mahoneyt944 will deal with this properly anyway.

**Comment by Wilstorm** [comment]
@barbudreadmon - I've always considered you knowledge and suggestions very sound (I still do). I think FBNeo is a fantastic core by all accounts. I'm trying to be objective as I can but I just don't quite understand why the particular stance on this update. Especially a toggle feels a bit over the top but kind of a cool idea for the nostalgic. 

I've heard you ask on the RP forums once why would anyone want to use mame2003-plus Donkey Kong when FBNeo has accurate colors. Now mame2003-plus can have those same accurate colors. Ding!? Wouldn't that be a great reason to support your fellow core. Some of the comments through the years on the RP forums you seem to steer folks away from mame2003-plus. To me this and FBNeo are the two best cores for low spec hardware so I support both and use both.

Tim is offering the share the work and information for the betterment of all. He's not fighting the core devs to add it. He's just saying hey guys I fixed up the colors for myself but if you all want to drop it into your core, I'll share the patch. I can't help to think it's awfully kind of him.

I would be in total agreement to add it to the ever changing progressive sister (mame2003-plus) and leave mame2003 as the snapshot core if someone prefers the inaccurate colors. 

If you calculate it out the ROM sets are probably about 97-98% identical so it should work perfectly for those folks who want the inaccurate. I would also think the folks that slant toward no changes would have no interest in the new additions anyway to mame2003-plus.

In a nutshell the RetroPie devs complained about all the changes (and occasional breaks), with growth comes growing pains right, but they decided to roll back the whole core after months of changes. They wanted it static with no changes to the ROM set. In the end, the fundamental structural changes being added to mame2003-plus, Grant decided to port over to mame2003 for all to benefit. Which was a perfect compromise. The core ROM set that is everywhere for that version is still viable but you have to do some hunting if you want to run the newer mame2003-plus.

Anyway to sum it up, then Mark, Arcadez & Grant spun up mame2003-plus and started really hammering out thousands of changes into the new core. Then later KMFDManic brought some great contemporary OST changes too, as well as, many other folks adding in small changes here and there (like this). I don't know the logistics of implementing the patch but overall this just feels like a win-win update. 

_I always thought mame2003-plus was a spin-off core that was designed for exactly these kind of changes!_

**Comment by mahoneyt944** [comment]
There is an issue open about this in 2003+
https://github.com/libretro/mame2003-plus-libretro/issues/1494

**Comment by mahoneyt944** [comment]
If the consensus is to add it here. It doesn't bother me at all. It's just colors. Or if we want to add it to 2003+ only, either is fine.

**Comment by Wilstorm** [comment]
@mahoneyt944 - I whole hardheartedly agree! 

There's certain games 2003+ has that FBNeo doesn't and vice versa. If this aligns them a little closer it sure feels like a step in the right direction.

**Comment by Wilstorm** [comment]
@MistyDreams ;-)

**Comment by Wilstorm** [comment]
I meant @MistyDreams comment above...I let the @ pull up the name list and pressed enter to soon on Mahoney...but either, or...both...it's all good! ;)

**Comment by barbudreadmon** [comment]
>I always thought mame2003-plus was a spin-off core that was designed for exactly these kind of changes!

@Wilstorm me too, and if backports are also being made to those mame snapshots now then i'd recommend updating the readmes accordingly and maybe adding some kind a changelog for those backports.

**Comment by mahoneyt944** [comment]
@barbudreadmon I think you're over reacting here. These are just colors. Technically in mame2003 these colors weren't considered wrong at that time, so when you changed the drivers to reflect "imperfect colors" that wasn't honoring the snapshot either.

**Pull request merged**
