### PR TITLE
Better Retropad defaults for CPS1 (Street Fighter 2 etc) and MAME UI

### PR DESCRIPTION
**Pull request by dankcushions**
Also removed the default binding for the MAME menu as R1. Heard lots of stories of friends/kids messing up the MAME defaults after bashing on the controller a few times. Keyboard is required to access it now. Ideally it goes away entirely once we've abstracted all the functionality :)

### CODE REVIEW

**Comment by twinaphex** [comment]
Requiring the keyboard for what? This goes a step too far for me. At no point in time should a keyboard ever be required when previously it didn't have to.

**Comment by dankcushions** [comment]
@twinaphex keyboard is required for the MAME TAB UI. Eg: 



Previously you could use L1 to access this menu. Ideally we'd just disable it entirely but there is still some MAME functionality that you can only get at via this menu.

But yeah, I agree. I think I should leave the UI key as it is as some devices won't have a keyboard! I I've reversed that part of the PR.

**Comment by twinaphex** [comment]
I agree with you that the default button for bringing up the MAME menu might be unfortunate. Can it be rebound with core remaps?

**Comment by dankcushions** [comment]
It can be remapped through the MAME UI itself but that's it right now. Maybe remaps could be extended to do something. I'll give it some thought :)

**Pull request merged**
