### PR TITLE
Revert Williams sound changes remove speedups

### PR DESCRIPTION
**Pull request by gamez-fan**
The speedups break the sound in the T-Unit version of Mortal Kombat

### CODE REVIEW

**Comment by gamez-fan** [comment]
Judge Dredd, Mortal Kombat and both NBA Jam games will have broken sound when using the
Williams speedhacks in MAME78, i can fix NBA Jam sound and there is another version of 
MK which wont be affected.

So i propose to revert the Williams sound core back to not having the speedhacks in the main
libretro-2003 build but keep them active in the other midway libretro build letting people
know about the performance improvements that can be gained for the Midway games
but at the expensense of sound problems in some others.

**Comment by nikkoman** [comment]
A core option (to be set "per game" for Mortal Kombat by the user) would be ideal!

What I don't get is how the game was previously running fine on my stock RPi3 without the "Finish him" bug.

**Comment by dankcushions** [comment]
@nikkoman this sound corruption with the speedhack didn't previously happen. it's only manifested itself following other recent changes. 

the speedhack is a core option already, but i agree with @twinaphex - the speedhack should work properly like it did before. midway driver is too demanding for the systems this core targets without it.

**Comment by twinaphex** [comment]
@dankcushions Could you try going on a bisect spree to see which change broke it?

**Comment by gamez-fan** [comment]
The Midway speedup's come in three flavours, TMS3410 CPU based, DCS soundcore and Williams
sound core, by the time MAME78 came around all of these were removed i see from looking
at the sources you guys added the CPU and DCS speedups back in but not the Williams ones
which give a significant performance boost to certain T and Y-Unit Midway games and
my recent commit took care off

The Williams speedups only affect the following drivers excluding MK 2 which uses DCS...........

mcr68.c
midytunit.c
midyunit.c
williams.c

When i added the Williams speedups to my MAME84 source the exact same thing happened eg
all games are fine soundwise except the T-Unit games which now had some problems around
the MSM6295 voices either not triggering or triggering incorrectly like we have seen reported
with regards to Mortal Kombat.

I was able to fix NBA Jam and Judge Dredd by changing the main CPU clockspeed but i could
not fix MK or NBA Jam TE so for my own source i have two Williams sound cores one with the
speedups and one without then i simply choose what games i want to boot via each core.
as we really need these on the Xbox.

In MAME61 the Williams speedhacks cause no problems soundwise and since the Midway code
and the sound cores these games used had no significant changes i came to the conclusion
that the big CPU plus memory and timer code changes come MAME79 is what was throwing
the sound off in MK for example with these speedhacks active in MAME84 if i turn off the hacks
the sound is fine but game takes nosedive in performance.

I only added the Williams speedups to this core as the code i mentioned above eg for the CPU
Mem and Timer handling is at MAME78 not all that much different from MAME61 so i assumed
the speedups would function in this core much the same as they did in the older core but that
seems to not be the case 

sorry about this guys if i'd known this would have happened i'd have left Williams sound well alone.

**Comment by twinaphex** [comment]
Sounds like you need to go back to the drawing board then for these games. Maybe revert it to what it was before, then carefully turn these changes you are making to these Williams/Midway drivers into optional things that we can enable/disable at will. One way of doing that is through core options.

Whatever the case, I don't want to lose the DCS speedhacks, that is the entire reason for mame 2003 to exist to begin with, it originally was a port of Lantus' MAME 078 for Xbox 360. Come up with a solution so that we can still enable those DCS speedhacks AND have a codepath that allows for increased accuracy. It should be possible to do both. I don't care how clean or not the code will look like as long as it is functional.

**Comment by gamez-fan** [comment]
You dont have to lose the DCS or TMS3410 CPU speedhacks those are not connected to
the Williams soundcore all im sayin is in order to fix the sound problems which have been
reported in the Midway T-Unit games all you have to do is revert back to the Williams
core you previously and have always used.

Obviously you'll lose the speedhacks on the Williams side of things but you never had them
before anyway so the Midway games will function as they always did in this MAME port
then myself or anyone who fancies giving it a go can look how at how to implement the 
Williams speedhacks in this core hopefully minus the sound problems.

**Comment by gamez-fan** [comment]
For the record it's this one that causes the sound problems...

#define DISABLE_FIRQ_SPEEDUP 0

**Comment by gamez-fan** [comment]
Ok lets stick with these speedhacks people can always use the Y-Unit version of Mortal Kombat
and i'll fix up NBA Jam sound shortly

**Comment by twinaphex** [comment]
OK, so DCS games were not affected by this? What was this regression that @dankcushions talked about?

Can we fix that regression? Was it the cause of some of these backported patches?

Can we compare performance of these games you say are affected by this speedhack before and after so we know exactly how much performance we are leaving on the table? I might be willing to leave the door open for these changes as long as the drawbacks are not too severe.

**Comment by gamez-fan** [comment]
You asked about performance this is what we got after adding the Williams speedhacks on Xbox
MAME different platform i know but you'll no doubt also get the same boosts or something
close to it on the Rpi..........

These are MAME84 values with the TMS3410 speedhacks active your older MAME78 core will
be faster to begin with so your boosts will likely be greater from the speedups

Midway Y-Unit minus Williams speedup
Narc 4fps unplayable 
Terminator 2 10fps unplayable
Mortal Kombat 10fps too slow
Smash TV drops to 15fps at times
Total Carnage drops to 15fps at times
All the other Y-Unit games would drop to half speed quite often.

Midway Y-Unit with added Williams speedup
Narc 45fps
All the other games constant full speed

Midway T-Unit minus the Williams speedup
NBA Jam / NBA Jam TE 4fps unplayable
Mortal Kombat 10fps too slow
Judge Dredd 10fps too slow
Mortal Kombat II unaffected uses DCS sound

Midway T-Unit with added Williams speedup
NBA Jam/ NBA Jam TE  30-35fps fully playable
Mortal Kombat full speed
Judge Dredd 40fps fully playable
Mortal Kombat II not affected uses DCS sound

**Comment by dankcushions** [comment]
my understanding now is that the DCS speedhack and Williams speedhack is different. This PR is reverting a speedhack that was not previously in mame2003.  presumably it is the revert of https://github.com/gamez-fan/mame2003-libretro/commit/503f2e5af245ef29768bffdc1293c86d0902386f#diff-eb7738781b616766446a231351712854

**Comment by gamez-fan** [comment]
Yes DCS and CPU based speedhacks would still be present!!!

**Comment by twinaphex** [comment]
OK, can we have the Williams speed hack behind a core option? Since that is still a rather large FPS difference, I'd like to have the ability to turn it on/off.

**Comment by gamez-fan** [comment]
@twinaphex it would be possible to set it up similar to how you have the DCS core option
did you add that yourself..?? unlike DCS however there are two speedhacks in Williams sound,,,,,,,,,

#define DISABLE_FIRQ_SPEEDUP		0
#define DISABLE_LOOP_CATCHERS		0

i suppose it's possible to rework both of the above into one handler to cutdown on the workload
then it's just a case of reusing the currant dcs speedhack code to make new core handling
for a williams speedhack enable / disable option

static unsigned williams_speedhack_enable = 0;

**Pull request closed without merging**
