### PR TITLE
Last few NeoGeo games

### PR DESCRIPTION
**Pull request by gamez-fan**
Added in the final few games plus a few extra decrypted versions, also tided up the driver

### CODE REVIEW

**Comment by twinaphex** [comment]
Hmm, can you resolve the conflict here?

**Comment by gamez-fan** [comment]
Removed conflicts but i have to ask is (UINT8 *)malloc correct..?? going by DRIVER INITS for games
which were supported already in the MAME78 driver malloc is the handler that is used.

**Comment by twinaphex** [comment]
I'd prefer if we use stdint types from now on - so instead of UINT8, uint8_t, etc.

Guess I can correct this manually, just something to keep in mind from now.

**Comment by twinaphex** [comment]
Hmm, ignore what I said, seems UINT8 is still used in a lot of places, so should be OK.

**Comment by Wilstorm** [comment]
@gamez-fan I've been trying to test these new games you've added but I can't seem to find these ROMs for testing. I am not sure if they are hacked but they are not port of the .193 set or the rollback, Could you help out here, please? :)

"The King of Fighters 2002 Plus"						kf2k2pa		neogeo.c
<rom name="262-p1p.bin" crc="758529a7"/>
<rom name="262-s1p.bin" crc="088657e6"/>

"Metal Slug 4 (Decrypted C)"							mslug4nd	neogeo.c
<rom name="ms4n_s1.rom" crc="c4f4ed0e"/>

"Metal Slug 5 (Decrypted C)"							mslug5nd	neogeo.c
<rom name="ms5n_c1.rom" crc="969c0d62"/>
<rom name="ms5n_c2.rom" crc="c69ae867"/>
<rom name="ms5n_c3.rom" crc=d7beaeaf"/>
<rom name="ms5n_c4.rom" crc="899fb2af"/>
<rom name="ms5n_c5.rom" crc="2fa1a5ad"/>
<rom name="ms5n_c6.rom" crc="6de89589"/>
<rom name="ms5n_c7.rom" crc="97bd0c0a"/>
<rom name="ms5n_c8.rom" crc="c0d5bc20"/>
<rom name="ms5n_s1.rom" crc="64952683"/>

"Zupapa!"									zupapa		neogeo.c
<rom name="267-v1d.bin" crc="1ac7db71"/>

**Comment by Wilstorm** [comment]
Updated comment and removed characters to display properly.

**Comment by gamez-fan** [comment]
These roms are from 15 years back you'd never find em nowadays and certainly not from sites
which carry the latest romsets, my advice would be forget about adding these to your dat file 
as they cant be tracked down anyhow.

Regards.

**Comment by Wilstorm** [comment]
Bummer, ok I was able to find many but these last few proved challenging and I was hoping you had access for testing the decrypted clones listed in the driver. Will remove them from the DAT.

**Comment by dankcushions** [comment]
hacked games won't be in current mame rom sets. they may be in FBA ones, though. looks like these ones are in FBA .42: https://docs.google.com/spreadsheets/d/1GaqIIoiWbzKHwZ52S2xCSDQXILo81Ls1mHK6czKGAtM/edit#gid=1671511927

**Comment by gamez-fan** [comment]
Ah thats right FBA supports those rom versions i plain forgot, thanks for the headsup although
part of me thinks even those ones will be two new.

**Comment by Wilstorm** [comment]
Ok it had all the KOF oldies just missing these ones now. Basically a few ROMs from Metal Slug (mslug4nd & mslug5nd) and Pochi & Nyaa (pnyaa) and the DAT will be complete.

"Metal Slug 4 (Decrypted C)"	mslug4nd	neogeo.c
"ms4n_s1.rom" crc="c4f4ed0e"

"Metal Slug 5 (Decrypted C)"	mslug5nd	neogeo.c
"ms5n_c1.rom" crc="969c0d62"
"ms5n_c2.rom" crc="c69ae867"
"ms5n_c3.rom" crc=d7beaeaf"
"ms5n_c4.rom" crc="899fb2af"
"ms5n_c5.rom" crc="2fa1a5ad"
"ms5n_c6.rom" crc="6de89589"
"ms5n_c7.rom" crc="97bd0c0a"
"ms5n_c8.rom" crc="c0d5bc20"
"ms5n_s1.rom" crc="64952683"

"Zupapa!"	zupapa	neogeo.c
"267-v1d.bin" crc="1ac7db71"

**Comment by Wilstorm** [comment]
@gamez-fan I found most of the ROMs but unfortunately there's a few that just don't seem to be tucked away anywhere I can find. Without the ROM listed below Pochi & Nyaa can't be run nor the clone as both rely on 267-v1d.bin. It seems all these missing ROMs are from WinKawaks sets. Is there any chance you can use a MAME ROM for Pochi & Nyaa or should I just remove it as unplayable? I can get you a list of all the hacked/unofficial ROMs used in your updates if it helps?

Metal Slug 4 (Decrypted C) [system: Neo-Geo - folder: mslug4nd - parent: mslug4 - size: 70mb]
missing rom: ms4n_s1.rom [size: -] [CRC32: c4f4ed0e]

Metal Slug 5 (Decrypted C) [system: Neo-Geo - folder: mslug5nd - parent: mslug5 - size: 26mb]
missing rom: ms5n_c4.rom [size: -] [CRC32: 899fb2af]

Pochi & Nyaa [system: Neo-Geo - folder: pnyaa - size: 23mb]
missing rom: 267-v1d.bin [size: -] [CRC32: 1ac7db71]

Pochi & Nyaa (Decrypted C) [system: Neo-Geo - folder: pnyaan - parent: pnyaa - size: 7mb]
missing rom: 267-v1d.bin [size: -] [CRC32: 1ac7db71]
missing rom: pnyaa_s1.rom [size: -] [CRC32: 88ffbb15]

**Comment by gamez-fan** [comment]
I suppose we could use this one lemmie know if you can track it down.........

ROM_START( pnyaa ) /* Encrypted Set */
	ROM_REGION( 0x100000, REGION_CPU1, 0 )
	ROM_LOAD16_WORD_SWAP( "267-p1.bin", 0x000000, 0x100000, CRC(112fe2c0) SHA1(01420e051f0bdbd4f68ce306a3738161b96f8ba8) )

	/* The Encrypted Boards do _not_ have an s1 rom, data for it comes from the Cx ROMs */
	ROM_REGION( 0x20000, REGION_GFX1, 0 )
	ROM_FILL( 0x000000, 0x20000, 0 )
	ROM_REGION( 0x20000, REGION_GFX2, 0 )
	ROM_LOAD( "sfix.sfx", 0x000000, 0x20000, CRC(354029fc) SHA1(4ae4bf23b4c2acff875775d4cbff5583893ce2a1) )

	ROM_REGION( 0x80000, REGION_USER4, 0 )
	/* Encrypted, we load it here for reference and replace with decrypted ROM */
	ROM_LOAD( "267-m1.bin", 0x00000, 0x80000, CRC(c7853ccd) SHA1(1b7a4c5093cf0fe3861ce44fd1d3b30c71ad0abe) )
	/* Decrypted */
	NEO_BIOS_SOUND_512K( "267-m1_decrypted.bin", CRC(d58eaa8e) SHA1(4c4faf1da671a41b4d854790eb623a40cb35f256) )

	ROM_REGION( 0x400000, REGION_SOUND1, ROMREGION_SOUNDONLY )
	/* Encrypted */
	ROM_LOAD( "267-v1.bin", 0x000000, 0x400000, CRC(e2e8e917) SHA1(7f412d55aebff3d38a225a88c632916295ab0584) )

	NO_DELTAT_REGION

	ROM_REGION( 0x1000000, REGION_GFX3, 0 )
	/* Encrypted */
	ROM_LOAD16_BYTE( "267-c1.bin", 0x0000000, 0x800000, BAD_DUMP CRC(2e20617a) SHA1(ed73724377a321aa024a5886eb148c416d4451aa) ) /* Plane 0,1 */
	ROM_LOAD16_BYTE( "267-c2.bin", 0x0000001, 0x800000, BAD_DUMP CRC(4edfa720) SHA1(1407a1d0d44f73c1a196c95d368d6451b17f6176) ) /* Plane 2,3 */
ROM_END

**Pull request merged**
