### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by r-type**
remove osd_malloc

### CODE REVIEW

**Comment by gamez-fan** [comment]
Ah i wasn't sure about osd_malloc i should have removed it to be on the safe side as i did
with the recent commit for Power Instinct Legends i'll check over my changes for anymore
instances of it and thanks for the headsup!!!.

**Comment by gamez-fan** [comment]
i've found a few more examples of osd_malloc in the Neogeo driver from looking at some of the
other code that was present in the MAME78 driver i think i should alter these to be malloc i'll do
it shortly

**Comment by r-type** [comment]
oh yes i've only look at the actual merged code and not the PR yet ,
but yes now I see 8 osd_malloc in PR #140.
cool if you can fix it before a merge.

**Comment by gamez-fan** [comment]
Already done and thanks again for the headsup cheers!!!

**Comment by twinaphex** [comment]
@gamez-fan - The core currently does not compile -

https://hastebin.com/emedicobix.sm

can you fix this?

**Pull request merged**
