### PR TITLE
fix some bad merge tags in XML DAT

### PR DESCRIPTION
**Pull request by markwkidd**

### CODE REVIEW

**Comment by Wilstorm** [comment]
Mark I was just curious why you removed the merge tags. Are you slowly making the DATs flat as most seem to prefer on the Pi? I noticed you just removed them for a few games.

**Comment by markwkidd** [comment]
Those merge tags are incompatible and can't be used. If you create a fresh ClrMamePro profile with the old/current DAT it will show you errors

**Comment by markwkidd** [comment]
@Wilstorm honestly I have thought about shifting to a non-merged only DAT. That may be something I submit in the future, it's just not what I'm doing here :)

**Comment by Wilstorm** [comment]
Ok, I think about 99% of the world outside of the Pi still use split-merge but the Pi community has kind of adopted non-merge as the standard. I do store all my ROMs split-merge for the space saving as a full set with CHD's is like around 400 or 500GB. 

I am ok with either really for the Pi as I keep the sets separate non-merge just for RetroPie. These older sets of 10 or 20GB non-merged doesn't seem like much anymore but if newer MAME sets starts working on future versions of the Pi using non-merge is going to be a beast to store and fit on Micro SD cards.

I don't know if it matters but I think the hydra ROM issue is inconsistency in the DAT. You can keep the merge info intact if you want to keep it as accurate as possible. The error _"Can't merge set due to equal names for different hashes"_ is due to ClrMamePro thinking the file hashes are different but they are actually equal. The issue is the tagging. 

Here's an example of one of the files below. The parent thinks it's a clean dump, the 1st clone thinks it's a bad dump and the 2nd clone thinks it's no dump. If you change all of them to "bad dump" it should clear the errors on a fresh load of the DAT. 

"No Dump" would work too or remove the status tag. Since the file exists I would say bad dump but things like size may be different once a clean dump is obtained due to a bad dump might not contain all the information in the dump but for this old set it will probably always be bad/no dump unless someone updates the driver.

**Parent ROM: (hydra)**
<rom name="hydr1037.bin" size="65536" crc="b974d3d0" sha1="67ecb17386f4be00c03661de14deff77b8ca85d0"/>

**Clone ROM: (hydrap)**
<rom name="hydr1037.bin" merge="hydr1037.bin" size="65536" crc="b974d3d0" sha1="67ecb17386f4be00c03661de14deff77b8ca85d0" status="baddump"/>

**Clone ROM: (hydrap2)**
<rom name="hydr1037.bin" size="65536" crc="b974d3d0" sha1="67ecb17386f4be00c03661de14deff77b8ca85d0" status="nodump"/>

**Comment by Wilstorm** [comment]
Updated comment above to display examples properly. I don't know how to display the opening bracket without it clearing the whole line.

**Comment by markwkidd** [comment]
You're right, the hydra issue is bad tagging, even though the crcs are accurate. I'll fix that in the PR right now.

**Pull request merged**
