### PR TITLE
add libretro-common files (didn't git add during the backport)

### PR DESCRIPTION
**Pull request by markwkidd**
I left out a `git add -A` somewhere along the line

### CODE REVIEW

**Comment by grant2258** [comment]
in src/libretro/mame.c

 info->library_name = "MAME 2003-plus"; needs changed  to  info->library_name = "MAME 2003";

**Comment by grant2258** [comment]
ill let mark do this so he can update his code and keep his workflow control

**Comment by grant2258** [comment]
@markwkidd  I just wanted to leave this to you so you can keep the workflow easier for yourself. It easier to keep track that way

**Comment by grant2258** [comment]
I like the work you are doing mark its a lot to take on though. I dont want to touch this code base till we are stable while your working on it. Ill just report anything i see and we can keep in sync that way

**Comment by markwkidd** [comment]
That works for me!

**Pull request merged**
