### PR TITLE
Update Makefile to compile in MIPS3 engine for x86

### PR DESCRIPTION
**Pull request by markwkidd**
This PR has makes two tweaks:

* Add logic to compile MIPS3 engine when ARCH = x86 as passed to make. ARCH = x86 is already specified in all but one x86 buildbot recipe
* If ARCH is not specified, try to detect if those host system is x86 and compile in support

In order for generic Linux x86 to benefit from this, the corresponding buildbot .conf will need an update in libretro-super.

I'm hoping for code review. @dankcushions I'd be glad of any input you have.

I've tested this makefile in Windows where it seems to be working fine, despite some other issues I'm having getting my MAME 2003 build environment set up under MYSYS2.  Any hints about that are also welcome.

### CODE REVIEW

**Comment by markwkidd** [comment]
Intended to address https://github.com/libretro/mame2003-libretro/issues/38

**Comment by dankcushions** [comment]
nice! but I think maybe this is a bit overworked. I did a similar thing before in a few lines: https://github.com/libretro/mame2003-libretro/compare/master...dankcushions:kinst - but it doesn't really matter.

i agree that the current Makefile styling/layout is a bit of a mess but I think it's best to do that in a separate commit if you want to fix it. I didn't bother :)

i never did the PR because i don't have a 32-bit build of RA in OSX (not sure there are binaries anywhere either) so i couldn't test :( however i'm sure this works fine so it gets my thumbs up :+1: 

i wonder how hard it is to make 32-bit ASM work in 64-bit? at some point, better computers should be running later versions of MAME I suppose.

**Comment by markwkidd** [comment]
Yes, I found myself having to fix indentation and whitespace issues to make sure I understood what was going on since I used this file to learn how Makefiles work. I see your point though.

I think I can pull out just the new functionality as its own PR pretty easily now. Then I'll see about a 'cleanup' PR that is more focused.

**Comment by markwkidd** [comment]
@dankcushions I backed out of all but the necessary changes. Pushed those changes to this PR so that's what you should see now.

**Comment by dankcushions** [comment]
Looks good to me :+1:  Can't really test as I don't have a x86 32-bit device. Could you squash the commits?

**Comment by markwkidd** [comment]
After an epic struggle I was able to squash commits 1 and 2, but it destroyed # 3. I added 3 back in but I think I'm going to give up. At least there is one less commit now than there were.

I think this repo is set to allow admins to "Squash and Merge" PRs so perhaps that will be the way.

**Comment by markwkidd** [comment]
@hizzlekizzle I know that you are also familiar with the Makefiles/build process. Do you see any red flags here?

**Comment by twinaphex** [comment]
Lets merge it and see how it goes then.

**Comment by markwkidd** [comment]
I can confirm that the updated Makefile is correctly adding the MIPS3 engine to the Windows x86 buildbot core. Hooray!

screenshot 2017-07-23 08 22 39

**Pull request merged**
