### PR TITLE
Big update for Kaneko16

### PR DESCRIPTION
**Pull request by gamez-fan**
A full WIP description will follow

### CODE REVIEW

**Comment by gamez-fan** [comment]
Code via iq_132 reworked for MAME-2003 here is the full WIP.........

Kaneko Toybox and Calc3 MCU simulation added to the driver which gets some more
games playable, i then added a couple of extra games some rare prototypes that were dumped
a couple of years back and finally updated the sound and video handling for some nice
improvements in that dept.

when rolling the driver back i made a point of keeping the original Roms from MAME78 for the
games that worked previously that means only Roms for the new working games will be required

Original working games no functional change unless stated

The Berlin Wall
Magical Crystals
Blaze On
Great 1000 Mile Rally (Fixed the parent as it didn't work new Rom required)
Great 1000 Mile Rally (Evolution Model)
Great 1000 Mile Rally (USA)
Sand Scorpian (I fixed the background gfx game now playable)
Mille Miglia 2: Great 1000 Miles Rally

New Working games Roms will be needed unless stated

Bakuretsu Breaker (Rom hasn't changed)
Bonk's Adventure
Blood Warrior
Pack'n Bang Bang
Wing Force
B.Rap Boys..??
B.Rap Boys Special..??
Shogun Warriors..??
Fujiyama Buster.??

?? denotes im unsure if those ones will work as they didn't in my test build but they may do
when using this MAME corei guess we'll find out when users give em a go.

**Comment by gamez-fan** [comment]
The games have some niggles around the graphical layer priorites hence the flag, you dont it
notice it much in the games but since they're not 100% in the graphical dept i thought it better
to leave the imperfect flag.

BTW how did ya get on with B.Rap Boys did it boot in this core..??

**Comment by msheehan79** [comment]
Ah no worries then, I wasn't sure if they were left over flags or not is all. I agree the flags make sense to leave if there are indeed remaining quirks :)

I tried Shogun Warriors but it did not work, I believe the error was missing certain files from the ROM. I have the MAME 0.78 and 0.139 roms but not much in between so I tried both of those sets. I suppose it is possible if I had the right ROM it would work but I don't have ready access to other versions beyond 0.78 and 0.139 to say for sure. If I have time later tonight or Monday I'll give B.Rap Boys a shot and let you know!

**Comment by msheehan79** [comment]
Had a chance to try B.Rap Boys. The MAME 0.78 ROM won't load and is missing a bunch of files/wrong checksums. With a MAME 0.139 ROM it does load and runs at 60fps consistent on my RPI3. But there is definitely issues with the graphics, the color palette is wrong. It doesn't make the game unplayable but it's not a small issue either. 

brapboys-171231-010146

**Comment by gamez-fan** [comment]
Thanks for testing B.Rap Boys i'll look over the code again later it's likely a problem with the
memory map as i had to split it into the older style eg read / write as opposed to a single map
maybe i made a mistake which is causing the pallette to write incorrectly might be the
video routines as well however.

**Comment by gamez-fan** [comment]
Ok i've sent a possible fix for B Rap Boys it's untested however as this game along with
Shogun Warriors will not boot in my test core " i get a black screen crash" which makes
me wonder why you can actually get it work at all in this one.??.

Anyway if they still dont work then i'll have to just demote them to not playable in the
driver assuming this core is either missing some graphical routines or M68k CPU code
that these games would require to function correctly.

**Comment by msheehan79** [comment]
Just tried the latest build - unfortunately it doesn't seem any different. Game loads but the video colors aren't right and no different from the previous build. I don't know if I would demote it to unplayable as it is definitely playable in this state - it just looks a little funny!

The only ROM I got to work was the 0.139 version of B.Rap Boys. Shogun Warriors also doesn't load at all for me with either the 0.78 or 0.139 version of the ROM.

**Comment by gamez-fan** [comment]
A site called doperoms will have the correct version you seek, one last thing regarding brapboys
it might be worth checking the dip switch option for the flipscreen as i know if that is set to on
the game will defo have gfx problems.

Try the flipscreen both off and on as sometimes dip code settings can get reversed if they are
are from newer cores as an older build can sometimes misread them, apart from that im all
outta ideas here as i've been all over the driver with a fine tooth comb and the code looks
correct.

**Pull request merged**
