### PR TITLE
fix segfault

### PR DESCRIPTION
**Pull request by grant2258**
fix segfault on exit

### CODE REVIEW

**Comment by bparker06** [comment]
Can someone explain how this does anything?

**Comment by grant2258** [comment]
https://en.cppreference.com/w/c/language/operator_precedence

**Comment by markwkidd** [comment]
Dang grant, that's awesome. Never in a million years would I have known to make this kind of fix.

**Comment by bparker06** [comment]
@grant2258 Sorry but I think this is just plain wrong. `!` has a higher precedence than `&&` anyway, but there is no confusion here from a compiler standpoint and this logic is well-defined in the standard; the compiler is not "guessing". Disassemble the library with and without this patch and you will see the output is EXACTLY the same. This PR is a no-op and whatever issue this claims to solve is simply not true.

**Comment by grant2258** [comment]
why is the segfault gone on linux 64 bit

**Comment by grant2258** [comment]
well spoke to radius he mentioned he received some info it might be the sound buffer so ill look into that. looks like it might be time will tell.

Code written without parenthesis is also harder to read and prone to errors with assumptions about precedence that are sometimes wrong. Im not going to argue on the moot point. If you think its sensible to not use parenthesis change it back.

**Pull request merged**
